a = int(1)
b = int(9)

print("a =", a)
print("b  =", b)
print("a + b =", a + b)
print("a - b =", b - a)
print("a * b =", a * b)
print("a ** b =", a ** b)
print("a % b =", a % b)
print("a // b =", a // b)